resolver: lts-22.36

packages:
- connexpay
- connexpay-optparse

extra-deps:
  - git: https://github.com/typeable/bucks.git
    commit: 9e378b675fe7fb88d5ddb3af068d82eb441f343c
  - git: https://github.com/typeable/req.git
    commit: 8829ac5197f7a4b3f04b7fdfc3ea66cfe70ab0a5
nix:
  packages: [zlib]
local-bin-path: bin
