resolver: lts-22.13

packages:
- connexpay
- connexpay-optparse

extra-deps:
  - git: https://github.com/typeable/bucks.git
    commit: 9e378b675fe7fb88d5ddb3af068d82eb441f343c

nix:
  packages: [zlib]
local-bin-path: bin
